
services:
  gateway:
      build: ./BE/gateway 
      environment:
        - ROUTES={"\/users":"http://user_api:8000", "\/trips":"http://trip_api:8000", "\/bookings":"http://booking_api:8000", "\/payments":"http://payment_api:8000","\/notifications":"http://notification_api:8000"}
        - JWT_SECRET=thuyen_user              # trùng với user service
        - JWT_ALG=HS256
      ports:
        - "8000:8000"
      volumes:
        - ./BE/gateway:/app   
      depends_on:
        - user_api
        # - trip_api
        # - booking_api
        - payment_api
        - notification_api

  user_api:
    build: ./BE/user_service
    ports:
      - "8001:8000"
    volumes:
      - ./BE/user_service:/app
    env_file:
      - ./BE/user_service/.env
    depends_on:
      - user_db

  user_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: btb_user_db
    ports:
      - "3312:3306"   # expose port khác bên ngoài để tránh trùng
    volumes:
      - btb_user_db_data:/var/lib/mysql  
    
  # trip_api:
  #   build: ./BE/trip_service
  #   ports:
  #     - "8003:8000" 
  #   volumes:
  #     - ./BE/trip_service:/app
  #   env_file:
  #     - ./BE/trip_service/.env
  #   environment:
  #     - USER_SERVICE_URL=http://user_api:8000
  #   depends_on:
  #     - trip_db

  # trip_db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: btb_trip_db
  #   ports:
  #     - "3313:3306"   # expose port khác bên ngoài để tránh trùng
  #   volumes:
  #     - trip_db_data:/var/lib/mysql 
    
  # booking_api:
  #   build: ./BE/booking_service
  #   ports:
  #     - "8003:8000" 
  #   volumes:
  #     - ./BE/booking_service:/app
  #   env_file:
  #     - ./BE/booking_service/.env
  #   environment:
  #     - USER_SERVICE_URL=http://user_api:8000
  #   depends_on:
  #     - booking_db

  # booking_db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: 123456
  #     MYSQL_DATABASE: btb_booking_db
  #   ports:
  #     - "3314:3306"   # expose port khác bên ngoài để tránh trùng
  #   volumes:
  #     - booking_db_data:/var/lib/mysql 

  notification_api:
    build: ./BE/notify_service
    ports:
      - "8004:8000"
    volumes:
      - ./BE/notify_service:/app
    env_file:
      - ./BE/notify_service/.env
    depends_on:
      - notification_db

  notification_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: btb_notification_db
    ports:
      - "3315:3306"   
    volumes:
      - btb_notification_db_data:/var/lib/mysql

  payment_api:
    build: ./BE/payment_service
    ports:
      - "8005:8000"
    volumes:
      - ./BE/payment_service:/app
    env_file:
      - ./BE/payment_service/.env
    depends_on:
      - payment_db 
      # - student_api

  payment_db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: btb_payment_db
    ports:
      - "3316:3306"   # expose port khác bên ngoài để tránh trùng
    volumes:
      - btb_payment_db_data:/var/lib/mysql

volumes: 
  btb_user_db_data:
  # btb_trip_db_data:
  # btb_booking_db_data:
  btb_payment_db_data:
  btb_notification_db_data:
